apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-prod
          image: gcr.io/project-1-400619/order
          imagePullPolicy: Always
          
          ports:
            - containerPort: 3000